### ISSUE TITLE
Login failed due to:  invalid_grant error processing request

### ISSUE THREAD

**Issue by goolied** [rbrasga/RedEraser#2]
Followed the instructions to set up a Client ID and Secret but when I run the script from terminal in Mac, I receive the following error: "Login failed due to: invalid_grant error processing request"

I've checked the credentials many times over and deleted the reddit script and created a new one and still receive this error. Any ideas why I'm being denied a connection?

**Comment by rbrasga** [comment]
You are right. 

* Make sure you have the latest praw plugin.

* Follow the directions here to create 
 a praw.ini file (I am going to add a sample one that you can just modify): https://praw.readthedocs.io/en/latest/getting_started/configuration/prawini.html

* I was able to reproduce your issue and this resolved it. I'll push the correct files soon.

**Comment by goolied** [comment]
Thanks for the updates. Now when I try running the script, I get the error "global name 'USERNAME' is not defined". However, I've set my username in the praw.ini file per the instructions. Do you know what I can do to fix it?
